name: 'wasm2js action'
author: "Jesus Hernandez"
description: "Use WebAssembly/binaryen's wasm2js in your workflows"
inputs:
  file:
    description: 'The wasm file'
    required: true
  output:
    description: 'The output js file'
    required: true
  options:
    description: 'Additional options to pass to wasm2js'
    required: false
    default: "-Os"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file }}
    - ${{ inputs.output }}
    - ${{ inputs.options }}
